apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../../bases
namespace: petclinic-uat
resources:
- namespace.yaml
patchesJson6902:
- target:
    group: route.openshift.io
    version: v1
    kind: Route
    name: petclinic
  path: route-patch.json
- target:
    group: apps.openshift.io
    version: v1
    kind: DeploymentConfig
    name: petclinic
  path: deploymentconfig-patch.json