apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cicd-project
  source:
    path: gitops/cicd/project
    repoURL: https://github.com/pittar/gitops-argocd.git
    targetRevision: rhpds
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sync:
    comparedTo:
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      source:
        path: gitops/cicd/project
        repoURL: https://github.com/pittar/gitops-argocd.git
        targetRevision: rhpds
