apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-local
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: config-project
  source:
    path: gitops/resources/config
    repoURL: git.url.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  sync:
    comparedTo:
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      source:
        path: gitops/resources/config
        repoURL: git.url.git
        targetRevision: master
